### ISSUE TITLE
2 Spirit healers in Shadowglen, Night Elf start

### ISSUE THREAD

**Issue by XayeCW** [11011010/BFA-Frankenstein-Core#23]
![image](https://github.com/11011010/BFA-Frankenstein-Core/assets/52622262/b855d02a-713c-4c73-9311-34418207e02d)

**Comment by XayeCW** [comment]
![image](https://github.com/11011010/BFA-Frankenstein-Core/assets/52622262/61bc301e-c36e-4ddb-a64a-8631e558a278)

Same when dead

**Comment by 11011010** [comment]
The second Spirit healer found a new place.
