### ISSUE TITLE
Mulgore 

### ISSUE THREAD

**Issue by ghostcbs** [11011010/BFA-Frankenstein-Core#6]
Name of your character: HoofOfLight
What is bugged: Level Balancing
Full description of Bug: Level balancing is still not working well. Still running into lower level or higher level mobs.

**Comment by 11011010** [comment]
Needs more info:  .npc info and I need the Entry:
There are a lot of npc which need fixing.

**Comment by 11011010** [comment]
fixed a lot of Mulgore scaling. Will be visible after next restart
