### ISSUE TITLE
Bloodtalon Raptor ID: 1960

### ISSUE THREAD

**Issue by CptFlipFlops** [11011010/BFA-Frankenstein-Core#7]
Character = Trolnprogres
NPC = Bloodtalon Raptor ID: 1960
Bug = the raptors are being displayed as aggressive instead of neutral 
Severity = minor

**Comment by 11011010** [comment]
fixed,  should be correct with next restart.

**Comment by 11011010** [comment]
seems to be not the case, will check another time

**Comment by 11011010** [comment]
checked and fixed
